import { useState } from 'react';
import { useGetAllClips, useGetAllVideos, useUpdateVideo, useDeleteVideo } from '../../hooks/useQueries';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
import { Label } from '../ui/label';
import { Card, CardContent, CardHeader, CardTitle } from '../ui/card';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '../ui/dialog';
import { Trash2, Edit, Star, Sparkles } from 'lucide-react';
import { toast } from 'sonner';
import type { VideoContent } from '../../backend';

export default function ClipsManagement() {
  const { data: clips, isLoading } = useGetAllClips();
  const { data: allVideos } = useGetAllVideos();
  const updateVideo = useUpdateVideo();
  const deleteVideo = useDeleteVideo();

  const [editingClip, setEditingClip] = useState<VideoContent | null>(null);
  const [editDialogOpen, setEditDialogOpen] = useState(false);
  const [clipCaption, setClipCaption] = useState('');

  const openEditDialog = (clip: VideoContent) => {
    setEditingClip(clip);
    setClipCaption(clip.clipCaption || '');
    setEditDialogOpen(true);
  };

  const handleUpdateSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!editingClip) return;

    try {
      const updatedClip: VideoContent = {
        ...editingClip,
        clipCaption: clipCaption || undefined,
      };

      await updateVideo.mutateAsync({ videoId: editingClip.id, video: updatedClip });
      toast.success('Clip updated successfully!');
      
      setEditDialogOpen(false);
      setEditingClip(null);
      setClipCaption('');
    } catch (error) {
      toast.error('Failed to update clip');
      console.error(error);
    }
  };

  const handleDelete = async (clipId: string) => {
    if (!confirm('Are you sure you want to delete this clip?')) return;
    
    try {
      await deleteVideo.mutateAsync(clipId);
      toast.success('Clip deleted successfully');
    } catch (error) {
      toast.error('Failed to delete clip');
      console.error(error);
    }
  };

  const getSourceVideoTitle = (sourceVideoId?: string): string | null => {
    if (!sourceVideoId || !allVideos) return null;
    const sourceVideo = allVideos.find(v => v.id === sourceVideoId);
    return sourceVideo?.title || null;
  };

  if (isLoading) {
    return <div className="text-center py-8">Loading clips...</div>;
  }

  return (
    <div className="space-y-6">
      <Card className="gradient-card border-2 border-primary/30">
        <CardHeader>
          <CardTitle>Manage Clips ({clips?.length || 0})</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {clips?.map((clip) => {
              const sourceTitle = getSourceVideoTitle(clip.sourceVideoId);
              const isAutoGenerated = !!clip.sourceVideoId;

              return (
                <div
                  key={clip.id}
                  className="flex items-center justify-between p-4 rounded-lg bg-black/60 border border-primary/20"
                >
                  <div className="flex items-center gap-4">
                    <img
                      src={clip.thumbnailUrl.getDirectURL()}
                      alt={clip.title}
                      className="w-24 h-16 object-cover rounded"
                    />
                    <div>
                      <h3 className="font-semibold flex items-center gap-2">
                        {clip.title}
                        {clip.isOriginal && <Star className="h-4 w-4 text-secondary fill-secondary" />}
                        {isAutoGenerated && (
                          <span title="Auto-generated clip">
                            <Sparkles className="h-4 w-4 text-primary" />
                          </span>
                        )}
                      </h3>
                      {clip.clipCaption && (
                        <p className="text-sm text-muted-foreground italic">{clip.clipCaption}</p>
                      )}
                      <p className="text-sm text-muted-foreground">{clip.description}</p>
                      {sourceTitle && (
                        <p className="text-xs text-primary/70 mt-1">Source: {sourceTitle}</p>
                      )}
                      <div className="flex gap-2 mt-1">
                        {clip.isPremium && (
                          <span className="text-xs bg-secondary/20 text-secondary px-2 py-0.5 rounded">Premium</span>
                        )}
                        <span className="text-xs bg-primary/20 text-primary px-2 py-0.5 rounded">Clip</span>
                        {isAutoGenerated && (
                          <span className="text-xs bg-primary/20 text-primary px-2 py-0.5 rounded">Auto-generated</span>
                        )}
                      </div>
                    </div>
                  </div>
                  <div className="flex gap-2">
                    <Button
                      variant="outline"
                      size="icon"
                      onClick={() => openEditDialog(clip)}
                      disabled={updateVideo.isPending}
                    >
                      <Edit className="h-4 w-4" />
                    </Button>
                    <Button
                      variant="destructive"
                      size="icon"
                      onClick={() => handleDelete(clip.id)}
                      disabled={deleteVideo.isPending}
                    >
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
              );
            })}
            {(!clips || clips.length === 0) && (
              <p className="text-center text-muted-foreground py-8">No clips available yet</p>
            )}
          </div>
        </CardContent>
      </Card>

      {/* Edit Dialog */}
      <Dialog open={editDialogOpen} onOpenChange={setEditDialogOpen}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>Edit Clip Caption</DialogTitle>
          </DialogHeader>
          <form onSubmit={handleUpdateSubmit} className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="clipCaption">Clip Caption</Label>
              <Input
                id="clipCaption"
                value={clipCaption}
                onChange={(e) => setClipCaption(e.target.value)}
                placeholder="e.g., Highlight, Quick View, Short"
              />
              <p className="text-xs text-muted-foreground">
                This caption helps distinguish different clips from the same source video.
              </p>
            </div>

            <div className="flex gap-2">
              <Button
                type="button"
                variant="outline"
                onClick={() => setEditDialogOpen(false)}
                className="flex-1"
              >
                Cancel
              </Button>
              <Button
                type="submit"
                disabled={updateVideo.isPending}
                className="flex-1 bg-gradient-to-r from-primary to-secondary"
              >
                {updateVideo.isPending ? 'Updating...' : 'Update Clip'}
              </Button>
            </div>
          </form>
        </DialogContent>
      </Dialog>
    </div>
  );
}
