/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdAssignment {
  'id' : string,
  'showOnFreeOnly' : boolean,
  'adIds' : Array<string>,
  'skipAfterSeconds' : [] | [bigint],
  'showCount' : bigint,
  'scope' : string,
  'position' : bigint,
  'targetId' : [] | [string],
}
export interface AdLocation {
  'adUrls' : Array<ExternalBlob>,
  'position' : bigint,
}
export interface AdMedia {
  'id' : string,
  'duration' : bigint,
  'tags' : [] | [Array<string>],
  'description' : string,
  'language' : [] | [string],
  'regions' : [] | [Array<string>],
  'adFile' : ExternalBlob,
  'mediaType' : string,
}
export interface Analytics {
  'subscriptionRevenue' : [] | [number],
  'totalViews' : bigint,
  'premiumUserCount' : bigint,
  'adImpressions' : bigint,
  'trendingContent' : Array<TrendingContent>,
  'categoryStats' : Array<CategoryStats>,
}
export interface Brand {
  'id' : string,
  'assignedFilms' : Array<string>,
  'logo' : [] | [ExternalBlob],
  'name' : string,
  'description' : string,
  'channels' : Array<Channel>,
  'assignedClips' : Array<string>,
  'assignedEpisodes' : Array<string>,
  'assignedLiveChannels' : Array<string>,
  'assignedSeries' : Array<string>,
}
export interface CategoryStats {
  'adImpressions' : bigint,
  'viewCount' : bigint,
  'premiumViews' : bigint,
  'category' : string,
}
export interface Channel {
  'id' : string,
  'name' : string,
  'description' : [] | [string],
  'branding' : string,
}
export type ContentType = { 'movie' : null } |
  { 'music' : null } |
  { 'documentary' : null } |
  { 'film' : null } |
  { 'news' : null } |
  { 'educational' : null } |
  { 'podcast' : null } |
  { 'series' : null } |
  { 'faithBased' : null } |
  { 'tvSeries' : null };
export interface Episode {
  'id' : string,
  'title' : string,
  'previewClipUrl' : [] | [ExternalBlob],
  'isFirstEpisode' : boolean,
  'thumbnailUrl' : ExternalBlob,
  'contentType' : ContentType,
  'isPremium' : boolean,
  'isOriginal' : boolean,
  'description' : string,
  'seasonId' : string,
  'episodeNumber' : bigint,
  'runtimeMinutes' : bigint,
  'videoUrl' : ExternalBlob,
}
export type ExternalBlob = Uint8Array;
export interface LiveChannel {
  'id' : string,
  'logo' : [] | [ExternalBlob],
  'name' : string,
  'isOriginal' : boolean,
  'schedule' : Array<ScheduledContent>,
}
export interface LiveChannelState {
  'currentProgram' : [] | [ScheduledContent],
  'isCommercialBreak' : [] | [boolean],
  'currentProgramTitle' : [] | [string],
  'isProgramPlaying' : [] | [boolean],
  'isLooping' : [] | [boolean],
  'availableAsVOD' : [] | [boolean],
  'currentTime' : [] | [bigint],
  'currentProgramStartTimestamp' : [] | [bigint],
  'programStartTime' : [] | [bigint],
  'channel' : LiveChannel,
  'currentProgramId' : [] | [string],
  'isContentAvailable' : [] | [boolean],
  'playbackPosition' : [] | [bigint],
}
export type LoginStatus = { 'admin' : UserProfile } |
  { 'regularUser' : UserProfile } |
  { 'anonymous' : null };
export interface RegisterInput {
  'password' : string,
  'name' : string,
  'email' : string,
}
export type RegularUserStatus = {
    'accessGranted' : { 'password' : string, 'userProfile' : UserProfile }
  } |
  { 'failed' : { 'error' : string } };
export interface ScheduledContent {
  'startTime' : bigint,
  'contentId' : string,
  'endTime' : bigint,
  'adLocations' : [] | [Array<AdLocation>],
  'isOriginal' : boolean,
}
export interface SearchResult {
  'id' : string,
  'title' : string,
  'thumbnailUrl' : [] | [ExternalBlob],
  'isPremium' : boolean,
  'isOriginal' : boolean,
  'description' : string,
  'resultType' : string,
}
export interface Season {
  'id' : string,
  'title' : string,
  'episodes' : Array<Episode>,
  'isOriginal' : boolean,
  'seasonNumber' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TVSeries {
  'id' : string,
  'title' : string,
  'previewClipUrl' : [] | [ExternalBlob],
  'thumbnailUrl' : ExternalBlob,
  'contentType' : ContentType,
  'seasons' : Array<Season>,
  'isOriginal' : boolean,
  'description' : string,
  'trailerUrl' : [] | [ExternalBlob],
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface TrendingContent {
  'id' : string,
  'title' : string,
  'viewCount' : bigint,
  'category' : string,
}
export interface UserProfile {
  'isPremium' : boolean,
  'name' : string,
  'email' : string,
  'hasPrioritySupport' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoContent {
  'id' : string,
  'title' : string,
  'previewClipUrl' : [] | [ExternalBlob],
  'thumbnailUrl' : ExternalBlob,
  'contentType' : ContentType,
  'isPremium' : boolean,
  'availableAsVOD' : boolean,
  'sourceVideoId' : [] | [string],
  'isOriginal' : boolean,
  'description' : string,
  'isClip' : boolean,
  'trailerUrl' : [] | [ExternalBlob],
  'genre' : [] | [string],
  'eligibleForLive' : boolean,
  'videoUrl' : ExternalBlob,
  'roles' : [] | [string],
  'releaseYear' : [] | [bigint],
  'clipCaption' : [] | [string],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addAdAssignment' : ActorMethod<[AdAssignment], undefined>,
  'addAdMedia' : ActorMethod<[AdMedia], undefined>,
  'addBrand' : ActorMethod<[Brand], undefined>,
  'addChannel' : ActorMethod<[Channel], undefined>,
  'addLiveChannel' : ActorMethod<[LiveChannel], undefined>,
  'addSeries' : ActorMethod<[TVSeries], undefined>,
  'addToWatchHistory' : ActorMethod<[string], undefined>,
  'addVideo' : ActorMethod<[VideoContent], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteAdAssignment' : ActorMethod<[string], undefined>,
  'deleteAdMedia' : ActorMethod<[string], undefined>,
  'deleteBrand' : ActorMethod<[string], undefined>,
  'deleteChannel' : ActorMethod<[string], undefined>,
  'deleteLiveChannel' : ActorMethod<[string], undefined>,
  'deleteSeries' : ActorMethod<[string], undefined>,
  'deleteVideo' : ActorMethod<[string], undefined>,
  'getAdAssignments' : ActorMethod<[], Array<AdAssignment>>,
  'getAdAssignmentsForLive' : ActorMethod<[string], Array<AdAssignment>>,
  'getAdMedia' : ActorMethod<[], Array<AdMedia>>,
  'getAllBrands' : ActorMethod<[], Array<Brand>>,
  'getAllClips' : ActorMethod<[], Array<VideoContent>>,
  'getAllSeries' : ActorMethod<[], Array<TVSeries>>,
  'getAllVideos' : ActorMethod<[], Array<VideoContent>>,
  'getAnalytics' : ActorMethod<[], Analytics>,
  'getBrandById' : ActorMethod<[string], [] | [Brand]>,
  'getCallerLoginStatus' : ActorMethod<[], LoginStatus>,
  'getCallerRegularUserStatus' : ActorMethod<[], RegularUserStatus>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChannelsByBrand' : ActorMethod<
    [string],
    {
      'films' : Array<string>,
      'episodes' : Array<string>,
      'clips' : Array<string>,
      'channels' : Array<Channel>,
      'series' : Array<string>,
      'liveChannels' : Array<string>,
    }
  >,
  'getDynamicLiveChannelState' : ActorMethod<[string], LiveChannelState>,
  'getEligibleVideosForLive' : ActorMethod<[], Array<VideoContent>>,
  'getLiveChannels' : ActorMethod<[], Array<LiveChannel>>,
  'getLiveChannelsByBrand' : ActorMethod<[string], Array<LiveChannel>>,
  'getSeriesById' : ActorMethod<[string], [] | [TVSeries]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getVideoById' : ActorMethod<[string], [] | [VideoContent]>,
  'getWatchHistory' : ActorMethod<[], Array<string>>,
  'incrementAdImpressions' : ActorMethod<[], undefined>,
  'incrementViews' : ActorMethod<[], undefined>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[string, string], boolean>,
  'register' : ActorMethod<[RegisterInput], undefined>,
  'search' : ActorMethod<[string], Array<SearchResult>>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAdAssignment' : ActorMethod<[string, AdAssignment], undefined>,
  'updateAdMedia' : ActorMethod<[string, AdMedia], undefined>,
  'updateBrand' : ActorMethod<[string, Brand], undefined>,
  'updateChannel' : ActorMethod<[string, Channel], undefined>,
  'updateLiveChannel' : ActorMethod<[string, LiveChannel], undefined>,
  'updateSeries' : ActorMethod<[string, TVSeries], undefined>,
  'updateVideo' : ActorMethod<[string, VideoContent], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];