/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AdAssignment = IDL.Record({
  'id' : IDL.Text,
  'showOnFreeOnly' : IDL.Bool,
  'adIds' : IDL.Vec(IDL.Text),
  'skipAfterSeconds' : IDL.Opt(IDL.Nat),
  'showCount' : IDL.Nat,
  'scope' : IDL.Text,
  'position' : IDL.Int,
  'targetId' : IDL.Opt(IDL.Text),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AdMedia = IDL.Record({
  'id' : IDL.Text,
  'duration' : IDL.Int,
  'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
  'description' : IDL.Text,
  'language' : IDL.Opt(IDL.Text),
  'regions' : IDL.Opt(IDL.Vec(IDL.Text)),
  'adFile' : ExternalBlob,
  'mediaType' : IDL.Text,
});
export const Channel = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
  'branding' : IDL.Text,
});
export const Brand = IDL.Record({
  'id' : IDL.Text,
  'assignedFilms' : IDL.Vec(IDL.Text),
  'logo' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'channels' : IDL.Vec(Channel),
  'assignedClips' : IDL.Vec(IDL.Text),
  'assignedEpisodes' : IDL.Vec(IDL.Text),
  'assignedLiveChannels' : IDL.Vec(IDL.Text),
  'assignedSeries' : IDL.Vec(IDL.Text),
});
export const AdLocation = IDL.Record({
  'adUrls' : IDL.Vec(ExternalBlob),
  'position' : IDL.Int,
});
export const ScheduledContent = IDL.Record({
  'startTime' : IDL.Int,
  'contentId' : IDL.Text,
  'endTime' : IDL.Int,
  'adLocations' : IDL.Opt(IDL.Vec(AdLocation)),
  'isOriginal' : IDL.Bool,
});
export const LiveChannel = IDL.Record({
  'id' : IDL.Text,
  'logo' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'isOriginal' : IDL.Bool,
  'schedule' : IDL.Vec(ScheduledContent),
});
export const ContentType = IDL.Variant({
  'movie' : IDL.Null,
  'music' : IDL.Null,
  'documentary' : IDL.Null,
  'film' : IDL.Null,
  'news' : IDL.Null,
  'educational' : IDL.Null,
  'podcast' : IDL.Null,
  'series' : IDL.Null,
  'faithBased' : IDL.Null,
  'tvSeries' : IDL.Null,
});
export const Episode = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'previewClipUrl' : IDL.Opt(ExternalBlob),
  'isFirstEpisode' : IDL.Bool,
  'thumbnailUrl' : ExternalBlob,
  'contentType' : ContentType,
  'isPremium' : IDL.Bool,
  'isOriginal' : IDL.Bool,
  'description' : IDL.Text,
  'seasonId' : IDL.Text,
  'episodeNumber' : IDL.Nat,
  'runtimeMinutes' : IDL.Nat,
  'videoUrl' : ExternalBlob,
});
export const Season = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'episodes' : IDL.Vec(Episode),
  'isOriginal' : IDL.Bool,
  'seasonNumber' : IDL.Nat,
});
export const TVSeries = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'previewClipUrl' : IDL.Opt(ExternalBlob),
  'thumbnailUrl' : ExternalBlob,
  'contentType' : ContentType,
  'seasons' : IDL.Vec(Season),
  'isOriginal' : IDL.Bool,
  'description' : IDL.Text,
  'trailerUrl' : IDL.Opt(ExternalBlob),
});
export const VideoContent = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'previewClipUrl' : IDL.Opt(ExternalBlob),
  'thumbnailUrl' : ExternalBlob,
  'contentType' : ContentType,
  'isPremium' : IDL.Bool,
  'isOriginal' : IDL.Bool,
  'description' : IDL.Text,
  'isClip' : IDL.Bool,
  'trailerUrl' : IDL.Opt(ExternalBlob),
  'genre' : IDL.Opt(IDL.Text),
  'videoUrl' : ExternalBlob,
  'roles' : IDL.Opt(IDL.Text),
  'releaseYear' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const TrendingContent = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'viewCount' : IDL.Nat,
  'category' : IDL.Text,
});
export const CategoryStats = IDL.Record({
  'adImpressions' : IDL.Nat,
  'viewCount' : IDL.Nat,
  'premiumViews' : IDL.Nat,
  'category' : IDL.Text,
});
export const Analytics = IDL.Record({
  'subscriptionRevenue' : IDL.Opt(IDL.Float64),
  'totalViews' : IDL.Nat,
  'premiumUserCount' : IDL.Nat,
  'adImpressions' : IDL.Nat,
  'trendingContent' : IDL.Vec(TrendingContent),
  'categoryStats' : IDL.Vec(CategoryStats),
});
export const UserProfile = IDL.Record({
  'isPremium' : IDL.Bool,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'hasPrioritySupport' : IDL.Bool,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const RegisterInput = IDL.Record({
  'password' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const SearchResult = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Opt(ExternalBlob),
  'isPremium' : IDL.Bool,
  'isOriginal' : IDL.Bool,
  'description' : IDL.Text,
  'resultType' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addAdAssignment' : IDL.Func([AdAssignment], [], []),
  'addAdMedia' : IDL.Func([AdMedia], [], []),
  'addBrand' : IDL.Func([Brand], [], []),
  'addChannel' : IDL.Func([Channel], [], []),
  'addLiveChannel' : IDL.Func([LiveChannel], [], []),
  'addSeries' : IDL.Func([TVSeries], [], []),
  'addToWatchHistory' : IDL.Func([IDL.Text], [], []),
  'addVideo' : IDL.Func([VideoContent], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteAdAssignment' : IDL.Func([IDL.Text], [], []),
  'deleteAdMedia' : IDL.Func([IDL.Text], [], []),
  'deleteBrand' : IDL.Func([IDL.Text], [], []),
  'deleteChannel' : IDL.Func([IDL.Text], [], []),
  'deleteLiveChannel' : IDL.Func([IDL.Text], [], []),
  'deleteSeries' : IDL.Func([IDL.Text], [], []),
  'deleteVideo' : IDL.Func([IDL.Text], [], []),
  'getAdAssignments' : IDL.Func([], [IDL.Vec(AdAssignment)], ['query']),
  'getAdMedia' : IDL.Func([], [IDL.Vec(AdMedia)], ['query']),
  'getAllBrands' : IDL.Func([], [IDL.Vec(Brand)], ['query']),
  'getAllClips' : IDL.Func([], [IDL.Vec(VideoContent)], ['query']),
  'getAllSeries' : IDL.Func([], [IDL.Vec(TVSeries)], ['query']),
  'getAllVideos' : IDL.Func([], [IDL.Vec(VideoContent)], ['query']),
  'getAnalytics' : IDL.Func([], [Analytics], ['query']),
  'getBrandById' : IDL.Func([IDL.Text], [IDL.Opt(Brand)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChannelsByBrand' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'films' : IDL.Vec(IDL.Text),
          'episodes' : IDL.Vec(IDL.Text),
          'clips' : IDL.Vec(IDL.Text),
          'channels' : IDL.Vec(Channel),
          'series' : IDL.Vec(IDL.Text),
          'liveChannels' : IDL.Vec(IDL.Text),
        }),
      ],
      ['query'],
    ),
  'getLiveChannels' : IDL.Func([], [IDL.Vec(LiveChannel)], ['query']),
  'getLiveChannelsByBrand' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LiveChannel)],
      ['query'],
    ),
  'getSeriesById' : IDL.Func([IDL.Text], [IDL.Opt(TVSeries)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideoById' : IDL.Func([IDL.Text], [IDL.Opt(VideoContent)], ['query']),
  'getWatchHistory' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'incrementAdImpressions' : IDL.Func([], [], []),
  'incrementViews' : IDL.Func([], [], []),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'register' : IDL.Func([RegisterInput], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'search' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], ['query']),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAdAssignment' : IDL.Func([IDL.Text, AdAssignment], [], []),
  'updateAdMedia' : IDL.Func([IDL.Text, AdMedia], [], []),
  'updateBrand' : IDL.Func([IDL.Text, Brand], [], []),
  'updateChannel' : IDL.Func([IDL.Text, Channel], [], []),
  'updateLiveChannel' : IDL.Func([IDL.Text, LiveChannel], [], []),
  'updateSeries' : IDL.Func([IDL.Text, TVSeries], [], []),
  'updateVideo' : IDL.Func([IDL.Text, VideoContent], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AdAssignment = IDL.Record({
    'id' : IDL.Text,
    'showOnFreeOnly' : IDL.Bool,
    'adIds' : IDL.Vec(IDL.Text),
    'skipAfterSeconds' : IDL.Opt(IDL.Nat),
    'showCount' : IDL.Nat,
    'scope' : IDL.Text,
    'position' : IDL.Int,
    'targetId' : IDL.Opt(IDL.Text),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AdMedia = IDL.Record({
    'id' : IDL.Text,
    'duration' : IDL.Int,
    'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
    'description' : IDL.Text,
    'language' : IDL.Opt(IDL.Text),
    'regions' : IDL.Opt(IDL.Vec(IDL.Text)),
    'adFile' : ExternalBlob,
    'mediaType' : IDL.Text,
  });
  const Channel = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'branding' : IDL.Text,
  });
  const Brand = IDL.Record({
    'id' : IDL.Text,
    'assignedFilms' : IDL.Vec(IDL.Text),
    'logo' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'channels' : IDL.Vec(Channel),
    'assignedClips' : IDL.Vec(IDL.Text),
    'assignedEpisodes' : IDL.Vec(IDL.Text),
    'assignedLiveChannels' : IDL.Vec(IDL.Text),
    'assignedSeries' : IDL.Vec(IDL.Text),
  });
  const AdLocation = IDL.Record({
    'adUrls' : IDL.Vec(ExternalBlob),
    'position' : IDL.Int,
  });
  const ScheduledContent = IDL.Record({
    'startTime' : IDL.Int,
    'contentId' : IDL.Text,
    'endTime' : IDL.Int,
    'adLocations' : IDL.Opt(IDL.Vec(AdLocation)),
    'isOriginal' : IDL.Bool,
  });
  const LiveChannel = IDL.Record({
    'id' : IDL.Text,
    'logo' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'isOriginal' : IDL.Bool,
    'schedule' : IDL.Vec(ScheduledContent),
  });
  const ContentType = IDL.Variant({
    'movie' : IDL.Null,
    'music' : IDL.Null,
    'documentary' : IDL.Null,
    'film' : IDL.Null,
    'news' : IDL.Null,
    'educational' : IDL.Null,
    'podcast' : IDL.Null,
    'series' : IDL.Null,
    'faithBased' : IDL.Null,
    'tvSeries' : IDL.Null,
  });
  const Episode = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'previewClipUrl' : IDL.Opt(ExternalBlob),
    'isFirstEpisode' : IDL.Bool,
    'thumbnailUrl' : ExternalBlob,
    'contentType' : ContentType,
    'isPremium' : IDL.Bool,
    'isOriginal' : IDL.Bool,
    'description' : IDL.Text,
    'seasonId' : IDL.Text,
    'episodeNumber' : IDL.Nat,
    'runtimeMinutes' : IDL.Nat,
    'videoUrl' : ExternalBlob,
  });
  const Season = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'episodes' : IDL.Vec(Episode),
    'isOriginal' : IDL.Bool,
    'seasonNumber' : IDL.Nat,
  });
  const TVSeries = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'previewClipUrl' : IDL.Opt(ExternalBlob),
    'thumbnailUrl' : ExternalBlob,
    'contentType' : ContentType,
    'seasons' : IDL.Vec(Season),
    'isOriginal' : IDL.Bool,
    'description' : IDL.Text,
    'trailerUrl' : IDL.Opt(ExternalBlob),
  });
  const VideoContent = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'previewClipUrl' : IDL.Opt(ExternalBlob),
    'thumbnailUrl' : ExternalBlob,
    'contentType' : ContentType,
    'isPremium' : IDL.Bool,
    'isOriginal' : IDL.Bool,
    'description' : IDL.Text,
    'isClip' : IDL.Bool,
    'trailerUrl' : IDL.Opt(ExternalBlob),
    'genre' : IDL.Opt(IDL.Text),
    'videoUrl' : ExternalBlob,
    'roles' : IDL.Opt(IDL.Text),
    'releaseYear' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const TrendingContent = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'viewCount' : IDL.Nat,
    'category' : IDL.Text,
  });
  const CategoryStats = IDL.Record({
    'adImpressions' : IDL.Nat,
    'viewCount' : IDL.Nat,
    'premiumViews' : IDL.Nat,
    'category' : IDL.Text,
  });
  const Analytics = IDL.Record({
    'subscriptionRevenue' : IDL.Opt(IDL.Float64),
    'totalViews' : IDL.Nat,
    'premiumUserCount' : IDL.Nat,
    'adImpressions' : IDL.Nat,
    'trendingContent' : IDL.Vec(TrendingContent),
    'categoryStats' : IDL.Vec(CategoryStats),
  });
  const UserProfile = IDL.Record({
    'isPremium' : IDL.Bool,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'hasPrioritySupport' : IDL.Bool,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const RegisterInput = IDL.Record({
    'password' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const SearchResult = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Opt(ExternalBlob),
    'isPremium' : IDL.Bool,
    'isOriginal' : IDL.Bool,
    'description' : IDL.Text,
    'resultType' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addAdAssignment' : IDL.Func([AdAssignment], [], []),
    'addAdMedia' : IDL.Func([AdMedia], [], []),
    'addBrand' : IDL.Func([Brand], [], []),
    'addChannel' : IDL.Func([Channel], [], []),
    'addLiveChannel' : IDL.Func([LiveChannel], [], []),
    'addSeries' : IDL.Func([TVSeries], [], []),
    'addToWatchHistory' : IDL.Func([IDL.Text], [], []),
    'addVideo' : IDL.Func([VideoContent], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteAdAssignment' : IDL.Func([IDL.Text], [], []),
    'deleteAdMedia' : IDL.Func([IDL.Text], [], []),
    'deleteBrand' : IDL.Func([IDL.Text], [], []),
    'deleteChannel' : IDL.Func([IDL.Text], [], []),
    'deleteLiveChannel' : IDL.Func([IDL.Text], [], []),
    'deleteSeries' : IDL.Func([IDL.Text], [], []),
    'deleteVideo' : IDL.Func([IDL.Text], [], []),
    'getAdAssignments' : IDL.Func([], [IDL.Vec(AdAssignment)], ['query']),
    'getAdMedia' : IDL.Func([], [IDL.Vec(AdMedia)], ['query']),
    'getAllBrands' : IDL.Func([], [IDL.Vec(Brand)], ['query']),
    'getAllClips' : IDL.Func([], [IDL.Vec(VideoContent)], ['query']),
    'getAllSeries' : IDL.Func([], [IDL.Vec(TVSeries)], ['query']),
    'getAllVideos' : IDL.Func([], [IDL.Vec(VideoContent)], ['query']),
    'getAnalytics' : IDL.Func([], [Analytics], ['query']),
    'getBrandById' : IDL.Func([IDL.Text], [IDL.Opt(Brand)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChannelsByBrand' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'films' : IDL.Vec(IDL.Text),
            'episodes' : IDL.Vec(IDL.Text),
            'clips' : IDL.Vec(IDL.Text),
            'channels' : IDL.Vec(Channel),
            'series' : IDL.Vec(IDL.Text),
            'liveChannels' : IDL.Vec(IDL.Text),
          }),
        ],
        ['query'],
      ),
    'getLiveChannels' : IDL.Func([], [IDL.Vec(LiveChannel)], ['query']),
    'getLiveChannelsByBrand' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LiveChannel)],
        ['query'],
      ),
    'getSeriesById' : IDL.Func([IDL.Text], [IDL.Opt(TVSeries)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideoById' : IDL.Func([IDL.Text], [IDL.Opt(VideoContent)], ['query']),
    'getWatchHistory' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'incrementAdImpressions' : IDL.Func([], [], []),
    'incrementViews' : IDL.Func([], [], []),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'register' : IDL.Func([RegisterInput], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'search' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], ['query']),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAdAssignment' : IDL.Func([IDL.Text, AdAssignment], [], []),
    'updateAdMedia' : IDL.Func([IDL.Text, AdMedia], [], []),
    'updateBrand' : IDL.Func([IDL.Text, Brand], [], []),
    'updateChannel' : IDL.Func([IDL.Text, Channel], [], []),
    'updateLiveChannel' : IDL.Func([IDL.Text, LiveChannel], [], []),
    'updateSeries' : IDL.Func([IDL.Text, TVSeries], [], []),
    'updateVideo' : IDL.Func([IDL.Text, VideoContent], [], []),
  });
};

export const init = ({ IDL }) => { return []; };